### ISSUE TITLE
`sunIsUp()` for given date

### ISSUE THREAD

**Issue by rathesDot** [spatie/sun#2]
According to the readme

> You can get determine if the sun is up at a specific moment by passing in instance of Carbon\Carbon to sunIsUp

But in the code, this function only checks if the current date `Carbon::now()` is between the sunrise and sunset of the **passed** date

It should check if the passed date is between that days sunrise/sunset, shouldn't it?

**Comment by freekmurze** [comment]
Thanks for reporting this. It is fixed in the latest release.
